name: Static Types
on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.pyi'
      - pyproject.toml
      - tox.ini
      - requirements/**
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '**.py'
      - '**.pyi'
      - pyproject.toml
      - tox.ini
      - requirements/**
  schedule:
    - cron: 0 8 * * SAT

jobs:
  mypy:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Tox types env cache
        uses: actions/cache@v3
        with:
          path: .tox/types
          key: tox-types|${{ runner.os }}|${{ env.pythonLocation }}|${{ hashFiles('tox.ini') }}
      - name: Install tox
        run: pip install tox
      - name: Run mypy
        run: tox run -e types
